name: Example Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run job1
        run: echo "job: ${{ github.job }}"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Run job2
        run: echo "job: ${{ github.job }}"

  job3:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Run job3
        run: echo "job: ${{ github.job }}"

  job4:
    runs-on: ubuntu-latest
    needs: [job2, job3]
    steps:
      - name: Run job4
        run: echo "job: ${{ github.job }}"
