name: External Trigger

on:
  repository_dispatch:
    types:
      - incident_report

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug payload
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Payload:"
          echo '${{ toJson(github.event.client_payload) }}'

  
      
      
